// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AppSettingGroups.
    /// </summary>
    public static partial class AppSettingGroupsExtensions
    {
            /// <summary>
            /// Returns the App Setting Groups details for a given Group Path
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='groupPath'>
            /// The groups path in the format
            /// '\\\\Core\\\\Grandparent\\\\Parent\\\\Child'. MUST be URL encoded e.g.
            /// %5CCore%5CGrandParent%5CParent
            /// </param>
            public static AppSettingGroupDTO GetAppSettingGroupByPath(this IAppSettingGroups operations, string groupPath)
            {
                return Task.Factory.StartNew(s => ((IAppSettingGroups)s).GetAppSettingGroupByPathAsync(groupPath), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns the App Setting Groups details for a given Group Path
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='groupPath'>
            /// The groups path in the format
            /// '\\\\Core\\\\Grandparent\\\\Parent\\\\Child'. MUST be URL encoded e.g.
            /// %5CCore%5CGrandParent%5CParent
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AppSettingGroupDTO> GetAppSettingGroupByPathAsync(this IAppSettingGroups operations, string groupPath, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAppSettingGroupByPathWithHttpMessagesAsync(groupPath, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns all the App Setting Groups
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<AppSettingGroupDTO> GetAppSettingGroups(this IAppSettingGroups operations)
            {
                return Task.Factory.StartNew(s => ((IAppSettingGroups)s).GetAppSettingGroupsAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all the App Setting Groups
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<AppSettingGroupDTO>> GetAppSettingGroupsAsync(this IAppSettingGroups operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAppSettingGroupsWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns the App Setting Groups details for a single group Id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static AppSettingGroupDTO GetAppSettingGroup(this IAppSettingGroups operations, int id)
            {
                return Task.Factory.StartNew(s => ((IAppSettingGroups)s).GetAppSettingGroupAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns the App Setting Groups details for a single group Id
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<AppSettingGroupDTO> GetAppSettingGroupAsync(this IAppSettingGroups operations, int id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAppSettingGroupWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
