// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for AppSettings.
    /// </summary>
    public static partial class AppSettingsExtensions
    {
            /// <summary>
            /// Returns RESULTANT App Settings for a given Tenant and AppSettingsGroup. NO
            /// internal settings published.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The Id of the Tenant whose settings to return. This should be hard
            /// configured in the internal application config.
            /// </param>
            /// <param name='appSettingGroupId'>
            /// The AppSetting Group Id (i.e. the type of client). This should be hard
            /// configured in the internal application config.
            /// </param>
            public static IList<AppSettingDTO> GetAppSettings(this IAppSettings operations, int tenantId, int appSettingGroupId)
            {
                return Task.Factory.StartNew(s => ((IAppSettings)s).GetAppSettingsAsync(tenantId, appSettingGroupId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns RESULTANT App Settings for a given Tenant and AppSettingsGroup. NO
            /// internal settings published.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tenantId'>
            /// The Id of the Tenant whose settings to return. This should be hard
            /// configured in the internal application config.
            /// </param>
            /// <param name='appSettingGroupId'>
            /// The AppSetting Group Id (i.e. the type of client). This should be hard
            /// configured in the internal application config.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<AppSettingDTO>> GetAppSettingsAsync(this IAppSettings operations, int tenantId, int appSettingGroupId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAppSettingsWithHttpMessagesAsync(tenantId, appSettingGroupId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
