// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// AppSettings operations.
    /// </summary>
    public partial interface IAppSettings
    {
        /// <summary>
        /// Returns RESULTANT App Settings for a given Tenant and
        /// AppSettingsGroup. NO internal settings published.
        /// </summary>
        /// <param name='tenantId'>
        /// The Id of the Tenant whose settings to return. This should be hard
        /// configured in the internal application config.
        /// </param>
        /// <param name='appSettingGroupId'>
        /// The AppSetting Group Id (i.e. the type of client). This should be
        /// hard configured in the internal application config.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<AppSettingDTO>>> GetAppSettingsWithHttpMessagesAsync(int tenantId, int appSettingGroupId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
