// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// AppSettingSections operations.
    /// </summary>
    public partial interface IAppSettingSections
    {
        /// <summary>
        /// Get App Setting Section details by id
        /// </summary>
        /// <param name='appSettingSectionId'>
        /// App Setting Section Id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<AppSettingSectionDTO>> GetAppSettingSectionWithHttpMessagesAsync(int appSettingSectionId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Update an existing App Setting Section
        /// </summary>
        /// <param name='appSettingSectionId'>
        /// App Setting Section Id
        /// </param>
        /// <param name='appSettingSectionDTO'>
        /// App Setting Section DTO
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse> PutAppSettingSectionWithHttpMessagesAsync(int appSettingSectionId, AppSettingSectionDTO appSettingSectionDTO, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Delete a AppSettingSection
        /// </summary>
        /// <param name='appSettingSectionId'>
        /// The App Setting Section Id
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<AppSettingSectionDTO>> DeleteAppSettingSectionWithHttpMessagesAsync(int appSettingSectionId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Returns all Sections
        /// </summary>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<AppSettingSectionDTO>>> GetAppSettingSectionsWithHttpMessagesAsync(Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Add an App Setting Section
        /// </summary>
        /// <param name='appSettingSectionDTO'>
        /// The new appSettingSection DTO
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<AppSettingSectionDTO>> PostAppSettingSectionWithHttpMessagesAsync(AppSettingSectionDTO appSettingSectionDTO, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
