// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Application Setting
    /// </summary>
    public partial class AppSettingDTO
    {
        /// <summary>
        /// Initializes a new instance of the AppSettingDTO class.
        /// </summary>
        public AppSettingDTO() { }

        /// <summary>
        /// Initializes a new instance of the AppSettingDTO class.
        /// </summary>
        public AppSettingDTO(string appSettingId = default(string), string settingKey = default(string), int? tenantId = default(int?), string settingGroupId = default(string), string groupPath = default(string), string settingSectionId = default(string), int? typeId = default(int?), string settingValue = default(string), bool? isLocked = default(bool?), bool? isInternalOnly = default(bool?), string description = default(string), DateTime? modifiedDate = default(DateTime?), string modifiedBy = default(string))
        {
            AppSettingId = appSettingId;
            SettingKey = settingKey;
            TenantId = tenantId;
            SettingGroupId = settingGroupId;
            GroupPath = groupPath;
            SettingSectionId = settingSectionId;
            TypeId = typeId;
            SettingValue = settingValue;
            IsLocked = isLocked;
            IsInternalOnly = isInternalOnly;
            Description = description;
            ModifiedDate = modifiedDate;
            ModifiedBy = modifiedBy;
        }

        /// <summary>
        /// The setting Id
        /// </summary>
        [JsonProperty(PropertyName = "AppSettingId")]
        public string AppSettingId { get; set; }

        /// <summary>
        /// Setting Key
        /// </summary>
        [JsonProperty(PropertyName = "SettingKey")]
        public string SettingKey { get; set; }

        /// <summary>
        /// Tenant Id. Zero indicates that this setting applies to all
        /// affiliates unless overridden
        /// </summary>
        [JsonProperty(PropertyName = "TenantId")]
        public int? TenantId { get; set; }

        /// <summary>
        /// The group that this setting applies to. Each client is will be
        /// interested in the settings contained in a group and it's parent
        /// groups
        /// </summary>
        [JsonProperty(PropertyName = "SettingGroupId")]
        public string SettingGroupId { get; set; }

        /// <summary>
        /// The group path
        /// </summary>
        [JsonProperty(PropertyName = "GroupPath")]
        public string GroupPath { get; set; }

        /// <summary>
        /// The setting UI section
        /// </summary>
        [JsonProperty(PropertyName = "SettingSectionId")]
        public string SettingSectionId { get; set; }

        /// <summary>
        /// The type of setting value. e.g. HTML, TEXT,
        /// </summary>
        [JsonProperty(PropertyName = "TypeId")]
        public int? TypeId { get; set; }

        /// <summary>
        /// The setting value.
        /// </summary>
        [JsonProperty(PropertyName = "SettingValue")]
        public string SettingValue { get; set; }

        /// <summary>
        /// Indicates that this setting can not be edited in the DCR Admin UI
        /// </summary>
        [JsonProperty(PropertyName = "IsLocked")]
        public bool? IsLocked { get; set; }

        /// <summary>
        /// Indicates that this setting should be hidden to all public
        /// requests.
        /// </summary>
        [JsonProperty(PropertyName = "IsInternalOnly")]
        public bool? IsInternalOnly { get; set; }

        /// <summary>
        /// Description of the App Setting
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Last modified date and time
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDate")]
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// Modified by
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedBy")]
        public string ModifiedBy { get; set; }

    }
}
