// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace hms.entappsettings.webapi.clientsdk.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Tenant
    /// </summary>
    public partial class TenantDTO
    {
        /// <summary>
        /// Initializes a new instance of the TenantDTO class.
        /// </summary>
        public TenantDTO() { }

        /// <summary>
        /// Initializes a new instance of the TenantDTO class.
        /// </summary>
        public TenantDTO(int? tenantId = default(int?), string tenantName = default(string), string tenantCode = default(string), string tenantDescription = default(string), DateTime? modifiedDate = default(DateTime?), string modifiedBy = default(string))
        {
            TenantId = tenantId;
            TenantName = tenantName;
            TenantCode = tenantCode;
            TenantDescription = tenantDescription;
            ModifiedDate = modifiedDate;
            ModifiedBy = modifiedBy;
        }

        /// <summary>
        /// Unique Tenant Id
        /// </summary>
        [JsonProperty(PropertyName = "TenantId")]
        public int? TenantId { get; set; }

        /// <summary>
        /// Tenant name (public display)
        /// </summary>
        [JsonProperty(PropertyName = "TenantName")]
        public string TenantName { get; set; }

        /// <summary>
        /// Tenant code (used for reporting and reference)
        /// </summary>
        [JsonProperty(PropertyName = "TenantCode")]
        public string TenantCode { get; set; }

        /// <summary>
        /// Tenant Description
        /// </summary>
        [JsonProperty(PropertyName = "TenantDescription")]
        public string TenantDescription { get; set; }

        /// <summary>
        /// Date last modified
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDate")]
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// Last modified by
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedBy")]
        public string ModifiedBy { get; set; }

    }
}
