// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.model
{

    // AppSetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSetting
    {
        public int AppSettingId { get; set; } // AppSettingId (Primary key)
        public string SettingKey { get; set; } // SettingKey (length: 50)
        public int TenantId { get; set; } // TenantId
        public int SettingGroupId { get; set; } // SettingGroupId
        public int SettingSectionId { get; set; } // SettingSectionId
        public Enums.SettingType TypeId { get; set; } // TypeId
        public string SettingValue { get; set; } // SettingValue
        public bool IsLocked { get; set; } // IsLocked
        public bool IsInternalOnly { get; set; } // IsInternalOnly
        public string Description { get; set; } // Description (length: 1000)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)

        // Foreign keys
        public virtual AppSettingGroup AppSettingGroup { get; set; } // FK_AppSetting_AppSettingGroup
        public virtual AppSettingSection AppSettingSection { get; set; } // FK_AppSetting_AppSettingSection
        public virtual AppSettingType AppSettingType { get; set; } // FK_AppSetting_AppSettingType
        public virtual Tenant Tenant { get; set; } // FK_AppSetting_Tenant

        public AppSetting()
        {
            TenantId = 0;
            SettingGroupId = 0;
            SettingSectionId = 0;
            SettingValue = "";
            IsLocked = false;
            IsInternalOnly = false;
            ModifiedDate = System.DateTime.UtcNow;
            ModifiedBy = "suser_sname()";
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
