// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.model
{

    // AppSettingType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSettingType
    {
        public Enums.SettingType AppSettingTypeId { get; set; } // AppSettingTypeId (Primary key)
        public string AppSettingType_ { get; set; } // AppSettingType (length: 50)
        public string AppSettingTypeDescription { get; set; } // AppSettingTypeDescription (length: 200)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AppSetting> AppSettings { get; set; } // AppSetting.FK_AppSetting_AppSettingType

        public AppSettingType()
        {
            ModifiedDate = System.DateTime.UtcNow;
            ModifiedBy = "suser_sname()";
            AppSettings = new System.Collections.Generic.List<AppSetting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
