// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.model
{

    // AppSettingGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSettingGroup
    {
        public int AppSettingGroupId { get; set; } // AppSettingGroupId (Primary key)
        public int? ParentGroupId { get; set; } // ParentGroupId
        public string Group { get; set; } // Group (length: 50)
        public string Description { get; set; } // Description (length: 1000)
        public string GroupPath { get; private set; } // GroupPath (length: 1000)
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate
        public string ModifiedBy { get; set; } // ModifiedBy (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AppSetting> AppSettings { get; set; } // AppSetting.FK_AppSetting_AppSettingGroup
        public virtual System.Collections.Generic.ICollection<AppSettingGroup> AppSettingGroups { get; set; } // AppSettingGroup.FK_AppSettingGroup_AppSettingGroup

        // Foreign keys
        public virtual AppSettingGroup ParentGroup { get; set; } // FK_AppSettingGroup_AppSettingGroup

        public AppSettingGroup()
        {
            ModifiedDate = System.DateTime.UtcNow;
            ModifiedBy = "suser_sname()";
            AppSettings = new System.Collections.Generic.List<AppSetting>();
            AppSettingGroups = new System.Collections.Generic.List<AppSettingGroup>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
