// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.context
{
    using hms.entappsettings.model;

    // AppSetting
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppSetting>
    {
        public AppSettingConfiguration()
            : this("dbo")
        {
        }

        public AppSettingConfiguration(string schema)
        {
            ToTable("AppSetting", schema);
            HasKey(x => x.AppSettingId);

            Property(x => x.AppSettingId).HasColumnName(@"AppSettingId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SettingKey).HasColumnName(@"SettingKey").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.TenantId).HasColumnName(@"TenantId").HasColumnType("int").IsRequired();
            Property(x => x.SettingGroupId).HasColumnName(@"SettingGroupId").HasColumnType("int").IsRequired();
            Property(x => x.SettingSectionId).HasColumnName(@"SettingSectionId").HasColumnType("int").IsRequired();
            Property(x => x.TypeId).HasColumnName(@"TypeId").HasColumnType("int").IsRequired();
            Property(x => x.SettingValue).HasColumnName(@"SettingValue").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.IsLocked).HasColumnName(@"IsLocked").HasColumnType("bit").IsRequired();
            Property(x => x.IsInternalOnly).HasColumnName(@"IsInternalOnly").HasColumnType("bit").IsRequired();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);

            // Foreign keys
            HasRequired(a => a.AppSettingGroup).WithMany(b => b.AppSettings).HasForeignKey(c => c.SettingGroupId); // FK_AppSetting_AppSettingGroup
            HasRequired(a => a.AppSettingSection).WithMany(b => b.AppSettings).HasForeignKey(c => c.SettingSectionId); // FK_AppSetting_AppSettingSection
            HasRequired(a => a.AppSettingType).WithMany(b => b.AppSettings).HasForeignKey(c => c.TypeId); // FK_AppSetting_AppSettingType
            HasRequired(a => a.Tenant).WithMany(b => b.AppSettings).HasForeignKey(c => c.TenantId); // FK_AppSetting_Tenant
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
