// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.context
{
    using hms.entappsettings.model;

    // AppSettingGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSettingGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppSettingGroup>
    {
        public AppSettingGroupConfiguration()
            : this("dbo")
        {
        }

        public AppSettingGroupConfiguration(string schema)
        {
            ToTable("AppSettingGroup", schema);
            HasKey(x => x.AppSettingGroupId);

            Property(x => x.AppSettingGroupId).HasColumnName(@"AppSettingGroupId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ParentGroupId).HasColumnName(@"ParentGroupId").HasColumnType("int").IsOptional();
            Property(x => x.Group).HasColumnName(@"Group").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000);
            Property(x => x.GroupPath).HasColumnName(@"GroupPath").HasColumnType("nvarchar").IsOptional().HasMaxLength(1000).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Computed);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);

            // Foreign keys
            HasOptional(a => a.ParentGroup).WithMany(b => b.AppSettingGroups).HasForeignKey(c => c.ParentGroupId).WillCascadeOnDelete(false); // FK_AppSettingGroup_AppSettingGroup
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
