// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.context
{
    using hms.entappsettings.model;

    // AppSettingType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public partial class AppSettingTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AppSettingType>
    {
        public AppSettingTypeConfiguration()
            : this("dbo")
        {
        }

        public AppSettingTypeConfiguration(string schema)
        {
            ToTable("AppSettingType", schema);
            HasKey(x => x.AppSettingTypeId);

            Property(x => x.AppSettingTypeId).HasColumnName(@"AppSettingTypeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AppSettingType_).HasColumnName(@"AppSettingType").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.AppSettingTypeDescription).HasColumnName(@"AppSettingTypeDescription").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
