// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace hms.entappsettings.context
{
    using hms.entappsettings.model;

    public interface IEntAppSettingsDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AppSetting> AppSettings { get; set; } // AppSetting
        System.Data.Entity.DbSet<AppSettingGroup> AppSettingGroups { get; set; } // AppSettingGroup
        System.Data.Entity.DbSet<AppSettingSection> AppSettingSections { get; set; } // AppSettingSection
        System.Data.Entity.DbSet<AppSettingType> AppSettingTypes { get; set; } // AppSettingType
        System.Data.Entity.DbSet<Tenant> Tenants { get; set; } // Tenant

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        int ClearDownAuditTables(int? keepMonths);
        // ClearDownAuditTablesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)


        // Table Valued Functions
        System.Linq.IQueryable<GetChildAppSettingGroupsReturnModel> GetChildAppSettingGroups(int? appSettingGroupId);
        System.Linq.IQueryable<GetChildAppSettingSectionsReturnModel> GetChildAppSettingSections(int? appSettingSectionId);
        System.Linq.IQueryable<GetParentAppSettingGroupsReturnModel> GetParentAppSettingGroups(int? appSettingGroupId);
        System.Linq.IQueryable<GetParentAppSettingSectionsReturnModel> GetParentAppSettingSections(int? appSettingSectionId);
    }

}
// </auto-generated>
